apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-node-app
  labels:
    app: gitops-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-node-app
  template:
    metadata:
      labels:
        app: gitops-node-app
    spec:
      containers:
        - name: nodejs-app
          image: hemasweetaavt/gitops-nodejs-app:latest
          ports:
            - containerPort: 3000